<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('user')->insert([
            [
                'nama'        => 'Admin Realfood',
                'email'       => 'admin@realfood.id',
                'password'    => Hash::make('admin123'),
                'role'        => 'admin', 
                'alamat'      => 'Jl. Mastrip No. 164, Jember', 
                'no_hp'       => '081234567890',
                'foto_profil' => null,
                'status_email'=> 'verified',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama'        => 'Nia Santika Putri',
                'email'       => 'nia@gmail.com',
                'password'    => Hash::make('user123'),
                'role'        => 'user', 
                'alamat'      => 'Politeknik Negeri Jember', 
                'no_hp'       => '082134567891',
                'foto_profil' => null,
                'status_email'=> 'verified',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama'        => 'Salam',
                'email'       => 'user1@user.com',
                'password'    => Hash::make('user123'),
                'role'        => 'user', 
                'alamat'      => 'Jl. Kalimantan, Jember', 
                'no_hp'       => '085234567892',
                'foto_profil' => null,
                'status_email'=> 'verified',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama'        => 'Abdusi',
                'email'       => 'admin1@admin.com',
                'password'    => Hash::make('admin123'),
                'role'        => 'admin', 
                'alamat'      => 'Jl. Jawa, Jember', 
                'no_hp'       => '089234567893',
                'foto_profil' => null,
                'status_email'=> 'verified',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama'        => 'admin',
                'email'       => 'admin@admin.com',
                'password'    => Hash::make('admin123'),
                'role'        => 'admin', 
                'alamat'      => 'Jl. Sumbersari, Jember', 
                'no_hp'       => '087234567894',
                'foto_profil' => null,
                'status_email'=> 'verified',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama'         => 'Andi Wijaya',
                'email'        => 'andi@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Sumbersari, Jember', 
                'no_hp'        => '087234567894',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Rina Pratama',
                'email'        => 'rina@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Mastrip, Jember', 
                'no_hp'        => '087234567895',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Bambang Sudjatmiko',
                'email'        => 'bambang@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Kalimantan, Jember', 
                'no_hp'        => '087234567896',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Dewi Sartika',
                'email'        => 'dewi@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Jawa, Jember', 
                'no_hp'        => '087234567897',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Eko Prasetyo',
                'email'        => 'eko@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Gajah Mada, Jember', 
                'no_hp'        => '087234567898',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Siti Fatimah',
                'email'        => 'siti@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Hayam Wuruk, Jember', 
                'no_hp'        => '087234567899',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Fajar Ramadhan',
                'email'        => 'fajar@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Karimata, Jember', 
                'no_hp'        => '087234567800',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Gita Permata',
                'email'        => 'gita@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Danau Toba, Jember', 
                'no_hp'        => '087234567801',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Hendra Wijaya',
                'email'        => 'hendra@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Panjaitan, Jember', 
                'no_hp'        => '087234567802',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Indah Lestari',
                'email'        => 'indah@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Trunojoyo, Jember', 
                'no_hp'        => '087234567803',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Joko Susilo',
                'email'        => 'joko@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Letjen Suprapto, Jember', 
                'no_hp'        => '087234567804',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Kartika Putri',
                'email'        => 'kartika@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Teuku Umar, Jember', 
                'no_hp'        => '087234567805',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Lukman Hakim',
                'email'        => 'lukman@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Imam Bonjol, Jember', 
                'no_hp'        => '087234567806',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Maya Indah',
                'email'        => 'maya@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Diponegoro, Jember', 
                'no_hp'        => '087234567807',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'nama'         => 'Nanang Kosim',
                'email'        => 'nanang@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Ahmad Yani, Jember', 
                'no_hp'        => '087234567808',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
           [
                'nama'         => 'Olivia Wijaya',
                'email'        => 'olivia@example.com',
                'password'     => Hash::make('user123'),
                'role'         => 'user', 
                'alamat'       => 'Jl. Sudirman, Jember', 
                'no_hp'        => '087234567809',
                'foto_profil'  => null,
                'status_email' => 'verified',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            
        ]);
    }
}